/*
This will be an sial to ARM64 translator based on sial-arm.

Implemented by JOnathan Kimmitt based on an idea by Martin Richards (c) February 2012

15/01/2025
UNDER DEVELOPMENT
*/

SECTION "sial-arm"

GET "libhdr"

GET "sial.h"

GLOBAL {
sialin: ug
asmout; stdin; stdout

rdf; rdp; rdg; rdk; rdw; rdl; rdc
rdcode

pval; gval; kval; wval; lval; mval

scan
cvf; cvfp; cvfg; cvfk; cvfw; cvfl

sectname
modletter
charv
labnumber

// To hold register name strings
 X0; X1; X2; X3; X4; X5; X6; X7; X8; X9; X10; X11; X12; X13; X14; X15
}
  
LET start() = VALOF
{ LET argv = VEC 20
  LET v    = VEC 20
  LET cv   = VEC 256/bytesperword
  LET arg = VEC 20

  X0, X1, X2, X3  :=  "X0", "X1", "X2", "X3"
  X4, X5, X6      :=  "X4", "X5", "X6"
  X7, X8, X9      :=  "X7", "X8", "X9"
  X10, X11          :=  "X10", "X11"
  X12, X13, X14, X15 :=  "X12", "X13", "X14", "X15" 

/*
genLoadK(X4, 4)
genLoadK(X4, -4)
genLoadK(X5, 255)
genLoadK(X5, 256)
genLoadK(X5, 257)
newline()
writef("*nTesting genLdrStr*n")
genLdrStr("ldr", X4, X10, 12)
genLdrStr("ldr", X4, X10, -12)
genLdrStr("ldr", X4, X10, 255)
genLdrStr("str", X4, X11, 256)
genLdrStr("str", X4, X11, 257)
genLdrStr("str", X4, X11, -257)
newline()
RESULTIS 0
*/
  sectname := v
  sectname%0 := 0
  modletter := 'A'
  charv := cv
  labnumber := 0

  asmout := 0
  stdout := output()
  IF rdargs("FROM,TO/K", argv, 20)=0 DO
  { writes("Bad args for sial-arm*n")
    RESULTIS 20
  }
  UNLESS argv!0 DO argv!0 := "prog.sial"
  UNLESS argv!1 DO argv!1 := "prog.s"
  sialin := findinput(argv!0)
  IF sialin=0 DO
  { writef("Trouble with file %s*n", argv!0)
    RESULTIS 20
  }
  asmout := findoutput(argv!1)
   
  IF asmout=0 DO
  { writef("Trouble with file %s*n", argv!1)
    RESULTIS 20
  }
   
  writef("Converting %s to %s*n", argv!0, argv!1)
  selectinput(sialin)
  selectoutput(asmout)

  writef("// Code generated by sial-arm64*n*n")

  arg%0 := argv!1%0
  FOR I = 1 TO arg%0 DO SWITCHON argv!1%I INTO {
      CASE '/': CASE '.': arg%I := '_'; ENDCASE
      DEFAULT: arg%I := argv!1%I; ENDCASE
      }

  writef("*n .section __TEXT,__cstring,cstring_literals")
  writef("*n .global %s_STRINGS", arg)
  writef("*n%s_STRINGS:", arg)
  writef("*n .section __DATA, __data*n")
  writef("*n .p2align 12, 0x0*n")
  writef("*n .global %s_DATA", arg)
  writef("*n%s_DATA:", arg)
  writef("*n .section __TEXT, __text,regular,pure_instructions*n")
  writef("*n .p2align 12, 0x0*n")
  writef("*n .global %s_TEXT", arg)
  writef("*n%s_TEXT:", arg)
  scan(arg)
  endread()
  UNLESS asmout=stdout DO endwrite()
  selectoutput(stdout)
  writef("Conversion complete*n")
  RESULTIS 0
}

AND nextlab() = VALOF
{ labnumber := labnumber+1
  RESULTIS labnumber
}

// Argument may be of form Ln
AND rdcode(let) = VALOF
{ LET a, ch, neg = 0, ?, FALSE

  ch := rdch() REPEATWHILE ch='*s' | ch='*n'

  IF ch=endstreamch RESULTIS -1

  UNLESS ch=let DO error("Bad item, looking for %c found %c*n", let, ch)

  ch := rdch()

  IF ch='-' DO { neg := TRUE; ch := rdch() }

  WHILE '0'<=ch<='9' DO { a := 10*a + ch - '0'; ch := rdch()  }

  RESULTIS neg -> -a, a
}

AND rdf() = rdcode('F')
AND rdp() = VALOF { pval := rdcode('P'); RESULTIS pval }
AND rdg() = VALOF { gval := rdcode('G'); RESULTIS gval }
AND rdk() = VALOF { kval := rdcode('K'); RESULTIS kval }
AND rdw() = VALOF { wval := rdcode('W'); RESULTIS wval }
AND rdl() = VALOF { lval := rdcode('L'); RESULTIS lval }
AND rdm() = VALOF { mval := rdcode('M'); RESULTIS mval }
AND rdc() = rdcode('C')

AND error(mess, a, b, c) BE
{ LET out = output()
  UNLESS out=stdout DO
  { selectoutput(stdout)
    writef(mess, a, b, c)
    selectoutput(out)
  }
  writef(mess, a, b, c)
}

AND scan(arg) BE
{ LET op = rdf()

  SWITCHON op INTO

  { DEFAULT:       error("// Bad op %n*n", op); LOOP

    CASE -1:       RETURN
      
    CASE f_lp:     cvfp("LP") // a := P!n
                   genLdrStr("ldr", X4, X10, 8*pval)
                   ENDCASE
    CASE f_lg:     cvfg("LG") // a := G!n
                   genLdrStr("ldr", X4, X11, 8*gval)
                   ENDCASE
    CASE f_ll:     cvfl("LL") // a := !Ln
                   writef("*n adrp X4, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X4, X4, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   writef("*n ldr X4, [X4]")
                   ENDCASE

    CASE f_llp:    cvfp("LLP") // a := // P!n
                   genAddK(X4, X10, 8*pval)
                   writef("*n lsr X4, X4, #3")
                   ENDCASE
    CASE f_llg:    cvfg("LLG") // a := // G!n
                   genAddK(X4, X11, 8*gval)
                   writef("*n lsr X4, X4, #3")
                   ENDCASE
    CASE f_lll:    cvfl("LLL") // a := // !Ln
                   writef("*n adrp X4, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X4, X4, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   writef("*n lsr X4, X4, #3")
                   ENDCASE
    CASE f_lf:     cvfl("LF") // a := byte address of Ln
                   writef("*n adrp X4, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X4, X4, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   ENDCASE
    CASE f_lw:     cvfm("LW")
                   writef("*n adrp X4, %s_M%c%n @PAGE", arg, modletter, mval)
                   writef("*n add X4, X4, %s_M%c%n @PAGEOFF", arg, modletter, mval)
                   writef("*n ldr X4, [X4]")
                   ENDCASE

    CASE f_l:      cvfk("L") // a := n
                   genLoadK(X4, kval)
                   ENDCASE
    CASE f_lm:     cvfk("LM") // a := -n
    	 	   writes("*n// load negative")
                   genLoadK(X4, -kval)
                   ENDCASE

    CASE f_sp:     cvfp("sp") // P!n := a
                   genLdrStr("str", X4, X10, 8*pval)
                   ENDCASE
    CASE f_sg:     cvfg("SG") // G!n := a
                   genLdrStr("str", X4, X11, 8*gval)
                   ENDCASE
    CASE f_sl:     cvfl("SL") // !Ln := a
                   writef("*n adrp X1, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X1, X1, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   writef("*n str X4, [X1]")
                   ENDCASE

    CASE f_ap:     cvfp("AP") // a := a + P!n
                   genLdrStr("ldr", X1, X10, 8*pval)
                   writef("*n add X4, X4, X1")
                   ENDCASE
    CASE f_ag:     cvfg("AG") // a := a + G!n
                   genLdrStr("ldr", X1, X11, 8*gval)
                   writef("*n add X4, X4, X1")
                   ENDCASE
    CASE f_a:      cvfk("A") // a := a + n
                   genAddK(X4, X4, kval)
                   ENDCASE
    CASE f_s:      cvfk("S")  // a := a - n
                   genAddK(X4, X4, -kval)
                   ENDCASE

    CASE f_lkp:    cvfkp("LKP") // a := P!n!k
                   genLdrStr("ldr", X4, X10, 8*pval)
                   genLoadK(X1, 8*kval)
                   writef("*n ldr X4, [X1, X4, LSL #3]")
                   ENDCASE
    CASE f_lkg:    cvfkg("LKG") // a := G!n!k
                   genLdrStr("ldr", X4, X11, 8*gval)
                   genLoadK(X1, 8*kval)
                   writef("*n ldr X4, [X1, X4, LSL #3]")
                   ENDCASE
    CASE f_rv:     cvf("RV")  // a := ! a
                   writef("*n lsl X4, X4, #3")
                   writef("*n ldr X4, [X4]")
                   ENDCASE
    CASE f_rvp:    cvfp("RVP") // a := P!n!a
                   genLdrStr("ldr", X1, X10, 8*pval)
                   writef("*n lsl X1, X1, #3")
                   writef("*n ldr X4, [X1, X4, lsl #3]")
                   ENDCASE
    CASE f_rvk:    cvfk("RVK") // a := a!k
                   genLoadK(X1, 8*kval)
                   writef("*n ldr X4, [X1, X4, lsl #3]")
                   ENDCASE
    CASE f_st:     cvf("ST") // !a := b
                   writef("*n mov X1, #0")
                   writef("*n str X5, [X1, X4, lsl #3]")
                   ENDCASE
    CASE f_stp:    cvfp("STP") // P!n!a := b
                   genLdrStr("ldr", X1, X10, 8*pval)
                   writef("*n lsl X2, X4, #3")
                   writef("*n str X5, [X2, X1, lsl #3]")
                   ENDCASE
    CASE f_stk:    cvfk("STK") // a!k := b
                   genLoadK(X1, 8*kval)
                   writef("*n str X5, [X1, X4, lsl #3]")
                   ENDCASE
    CASE f_stkp:   cvfkp("STKP")  // P!n!k := a
                   genLdrStr("ldr", X1, X10, 8*pval)
                   genLoadK(X2, 8*kval)
                   writef("*n str X4, [X2, X1, lsl #3]")
                   ENDCASE
    CASE f_skg:    cvfkg("SKG") // G!n!k := a
                   genLdrStr("ldr", X1, X11, 8*gval)
                   genLoadK(X2, 8*kval)
                   writef("*n str X4, [X2, X1, lsl #3]")
                   ENDCASE
    CASE f_xst:    cvf("XST") // !b := a
                   writef("*n mov X1, #0")
                   writef("*n str X4, [X1, X5, lsl #3]")
                   ENDCASE

    CASE f_k:      cvfp("K") // Call  a(b,...) incrementing P by n
                 {
                   genAddK(X2, X10, 8*pval)         // NP = P + 8*pval
                   writef("*n mov X1, X4")         // X1 = a  -- the entry address
                   writef("*n mov X4, X5")         // a := b
                   writef("*n blr X1")
                 }
                   ENDCASE
    CASE f_kpg:    cvfpg("KPG") // Call Gg(a,...) incrementing P by n
                 {
                   genLdrStr("ldr", X1, X11, 8*gval)
                   genAddK(X2, X10, 8*pval)
                   writef("*n blr X1")
                 }
                   ENDCASE

    CASE f_neg:    cvf("NEG") // a := - a
                   writef("*n neg X4, X4") 
                   ENDCASE
    CASE f_not:    cvf("NOT") // a := ~ a
                   writef("*n mvn X4, X4") 
                   ENDCASE
    CASE f_abs:    cvf("ABS") // a := ABS a
                   writef("*n cmp X4, #0")
                   writef("*n cneg X4, X4, MI")
                   ENDCASE

    CASE f_xdiv:   cvf("XDIV") // a := a / b; c := ?
                   writef("*n sdiv X4, X4, X5")
                   ENDCASE
    CASE f_xrem:   cvf("XREM") // a := a REM b; c := ?
                   writef("*n sdiv X0, X5, X4")
                   writef("*n mul X4, X0, X4")
                   writef("*n sub X4, X5, X4")
                   ENDCASE
    CASE f_xsub:   cvf("XSUB") // a := a - b
                   writef("*n sub X4, X4, X5")
                   ENDCASE

    CASE f_mul:    cvf("MUL") // a := b * a; c := ?
                   writef("*n mul X4, X5, X4")
                   ENDCASE
    CASE f_div:    cvf("DIV")  // a := b / a; c := ?
                   writef("*n sdiv X4, X5, X4")
                   ENDCASE
    CASE f_rem:    cvf("REM") // a := b REM a; c := ?
                   writef("*n sdiv X0, X5, X4")
                   writef("*n mul X4, X0, X4")
                   writef("*n sub X4, X5, X4")
                   ENDCASE
    CASE f_add:    cvf("ADD") // a := b + a
                   writef("*n add X4, X5, X4")
                   ENDCASE
    CASE f_sub:    cvf("SUB") // a := b - a
                   writef("*n sub X4, X5, X4")
                   ENDCASE

    CASE f_eq:     cvf("EQ") // a := b = a
                   writef("*n cmp X5, X4")
                   writef("*n cset W4, eq")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ne:     cvf("NE") // a := b ~= a
                   writef("*n cmp X4, X5")
                   writef("*n cset W4, ne")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ls:     cvf("LS") // a := b < a
                   writef("*n cmp X5, X4")
                   writef("*n cset W4, lt")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_gr:     cvf("GR") // a := b > a
                   writef("*n cmp X5, X4")
                   writef("*n cset W4, gt")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_le:     cvf("LE") // a := b <= a
                   writef("*n cmp X5, X4")
                   writef("*n cset W4, le")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ge:     cvf("GE") // a := b >= a
                   writef("*n cmp X5, X4")
                   writef("*n cset W4, ge")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_eq0:    cvf("EQ") // a := a = 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, eq")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ne0:    cvf("NE") // a := a ~= 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, ne")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ls0:    cvf("LS") // a := a < 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, lt")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_gr0:    cvf("GR") // a := a > 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, gt")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_le0:    cvf("LE") // a := a <= 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, le")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE
    CASE f_ge0:    cvf("GE") // a := a >= 0
                   writef("*n cmp X4, #0")
                   writef("*n cset W4, ge")
                   writef("*n sxtw X4, W4")
		   writef("*n neg X4,X4")
                   ENDCASE

    CASE f_lsh:    cvf("LSH") // a := b << a; b := ?
                   writef("*n lsl X4, X5, X4")
                   ENDCASE
    CASE f_rsh:    cvf("RSH") // a := b >> a; b := ?
                   writef("*n lsr X4, X5, X4")
                   ENDCASE
    CASE f_and:    cvf("AND") // a := b & a 
                   writef("*n and X4, X5, X4") 
                   ENDCASE
    CASE f_or:     cvf("OR") // a := b | a 
                   writef("*n orr X4, X5, X4") 
                   ENDCASE
    CASE f_xor:    cvf("XOR") // a := b NEQV a
                   writef("*n eor X4, X5, X4") 
                   ENDCASE
    CASE f_eqv:    cvf("EQV") // a := b EQV a 
                   writef("*n eor X4, X5, X4") 
                   writef("*n mvn X4, X4") 
                   ENDCASE

    CASE f_gbyt:   cvf("GBYT") // a := b % a
                   writef("*n lsl X0, X5, #3") 
                   writef("*n add X4, X4, X0") 
                   writef("*n ldrb w4, [X4]") 
                   writef("*n uxtb X4, w4") 
                   ENDCASE
    CASE f_xgbyt:  cvf("XGBYT") // a := a % b 
                   writef("*n lsl X0, X4, #3") 
                   writef("*n add X5, X5, X0") 
                   writef("*n ldrb w4, [X5]") 
                   writef("*n uxtb X4, w4") 
                   ENDCASE
    CASE f_pbyt:   cvf("PBYT") // b % a := c
                   writef("*n lsl X0, X5, #3") 
                   writef("*n add X4, X4, X0") 
                   writef("*n strb w6, [X4]") 
                   ENDCASE
    CASE f_xpbyt:  cvf("XPBYT") // a % b := c 
                   writef("*n lsl X0, X4, #3") 
                   writef("*n add X5, X5, X0") 
                   writef("*n strb w6, [X5]") 
                   ENDCASE

// swb       Kn Ld K1 L1 ... Kn Ln   Binary chop switch, Ld default
    CASE f_swb:    cvswb(arg)
                   ENDCASE

// swl       Kn Ld L1 ... Ln         Label vector switch, Ld default
    CASE f_swl:    cvswl(arg)
                   ENDCASE

    CASE f_xch:    cvf("XCH") // swap a and b
                   writef("*n mov X1, X4")
                   writef("*n mov X4, X5")
                   writef("*n mov X5, X1")
                   ENDCASE
    CASE f_atb:    cvf("ATB") // b := a
                   writef("*n mov X5, X4")
                   ENDCASE
    CASE f_atc:    cvf("ATC") // c := a
                   writef("*n mov X6, X4")
                   ENDCASE
    CASE f_bta:    cvf("BTA") // a := b
                   writef("*n mov X4, X5")
                   ENDCASE
    CASE f_btc:    cvf("BTC") // c := b
                   writef("*n mov X6, X5")
                   ENDCASE
    CASE f_atblp:  cvfp("ATBLP") // b := a; a := P!n
                   writef("*n mov X5, X4")
                   genLdrStr("ldr", X4, X10, 8*pval)
                   ENDCASE
    CASE f_atblg:  cvfg("ATBLG") // b := a; a := G!n
                   writef("*n mov X5, X4")
                   genLdrStr("ldr", X4, X11, 8*gval)
                   ENDCASE
    CASE f_atbl:   cvfk("ATBL") // b := a; a := k
                   writef("*n mov X5, X4")
                   genLoadK(X4, kval)
                   ENDCASE

    CASE f_j:      cvfl("J") // jump to Ln
                   writef("*n b %s_L%c%n", arg, modletter, lval)
//                   writef("*n .ltorg*n")
                   ENDCASE
    CASE f_rtn:    cvf("RTN") // procedure return
                   writef("*n ldp X10, lr, [X10]*n ret")
//                   writef("*n .ltorg*n")
                   ENDCASE
    CASE f_goto:   cvf("GOTO") // jump to a
                   writef("*n br X4")
//                   writef("*n .ltorg*n")
                   ENDCASE

    CASE f_res:    cvf("RES")   // <res> := A
                                // <res> is already in A
                                // nothing to do
                   ENDCASE

    CASE f_ldres:  cvf("LSRES") // A := <res>
                                // A and B already set properly
                   ENDCASE

    CASE f_ikp:    cvfkp("IKP") // a := P!n + k; P!n := a
                   genLdrStr("ldr", X4, X10, 8*pval)
                   genAddK(X4, X4, kval)
                   genLdrStr("str", X4, X10, 8*pval)
                   ENDCASE
    CASE f_ikg:    cvfkg("IKG") // a := G!n + k; G!n := a
                   genLdrStr("ldr", X4, X11, 8*gval)
                   genAddK(X4, X4, kval)
                   genLdrStr("str", X4, X11, 8*gval)
                   ENDCASE
    CASE f_ikl:    cvfkl("IKL") // a := !Ln + k; !Ln := a
                   writef("*n adrp X1, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X1, X1, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   writef("*n ldr X4, [X1]")
                   genAddK(X4, X4, kval)
                   writef("*n str X4, [X1]")
                   ENDCASE
    CASE f_ip:     cvfp("ip") // a := P!n + a; P!n := a
                   genLdrStr("ldr", X1, X10, 8*pval)
                   writef("*n add X4, X1, X4")
                   genLdrStr("str", X4, X10, 8*pval)
                   ENDCASE
    CASE f_ig:     cvfg("IG") // a := G!n + a; G!n := a
                   genLdrStr("ldr", X1, X11, 8*gval)
                   writef("*n add X4, X1, X4")
                   genLdrStr("str", X4, X11, 8*gval)
                   ENDCASE
    CASE f_il:     cvfl("IL") // a := !Ln + a; !Ln := a
                   writef("*n adrp X0, %s_L%c%n @PAGE", arg, modletter, lval)
                   writef("*n add X0, X0, %s_L%c%n @PAGEOFF", arg, modletter, lval)
                   writef("*n ldr X1, [X0]")
                   writef("*n add X4, X4, X1")
                   writef("*n str X4, [X0]")
                   ENDCASE

    CASE f_jeq:    cvfl("JEQ") // Jump to Ln if b = a
                   writef("*n cmp X5, X4")
                   writef("*n beq %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jne:    cvfl("JNE") // Jump to Ln if b ~= a
                   writef("*n cmp X5, X4")
                   writef("*n bne %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jls:    cvfl("JLS") // Jump to Ln if b < a
                   writef("*n cmp X5, X4")
                   writef("*n blt %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jgr:    cvfl("JGR") // Jump to Ln if b > a
                   writef("*n cmp X5, X4")
                   writef("*n bgt %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jle:    cvfl("JLE") // Jump to Ln if b <= a
                   writef("*n cmp X5, X4")
                   writef("*n ble %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jge:    cvfl("JGE") // Jump to Ln if b >= a
                   writef("*n cmp X5, X4")
                   writef("*n bge %s_L%c%n", arg, modletter, lval)
                   ENDCASE

    CASE f_jeq0:   cvfl("JEQ0") // Jump to Ln if a = 0
                   writef("*n cmp X4, #0")
                   writef("*n beq %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jne0:   cvfl("JNE0") // Jump to Ln if a ~= 0
                   writef("*n cmp X4, #0")
                   writef("*n bne %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jls0:   cvfl("JLS0") // Jump to Ln if a < 0
                   writef("*n cmp X4, #0")
                   writef("*n blt %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jgr0:   cvfl("JGr0") // Jump to Ln if a > 0
                   writef("*n cmp X4, #0")
                   writef("*n bgt %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jle0:   cvfl("JLE0") // Jump to Ln if a <= 0
                   writef("*n cmp X4, #0")
                   writef("*n ble %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jge0:   cvfl("JGE0") // Jump to Ln if a >= 0
                   writef("*n cmp X4, #0")
                   writef("*n bge %s_L%c%n", arg, modletter, lval)
                   ENDCASE
    CASE f_jge0m:  cvfm("JGE0M") // Jump to Mn if a >= 0
                   writef("*n cmp X4, #0")
                   writef("*n bge %s_M%c%n", arg, modletter, mval)
                   ENDCASE

    // The following five opcodes are never generated by
    // the BCPL compiler
    CASE f_brk:    cvf("BRK") // Breakpoint instruction
                   writef("*n// unimplemented")
                   ENDCASE
    CASE f_nop:    cvf("NOP") // No operation
                   ENDCASE
    CASE f_chgco:  cvf("CHGCO") // Change coroutine
                   writef("*n// unimplemented")
                   ENDCASE
    CASE f_mdiv:   cvf("MDIV") // a := Muldiv(P!3, P!4, P!5) 
                   writef("*n// unimplemented")
                   ENDCASE
    CASE f_sys:    cvf("SYS") // System function
                   writef("*n// unimplemented")
                   ENDCASE

    CASE f_section:  cvfs("SECTION") // Name of section
                     FOR i = 0 TO charv%0 DO sectname%i := charv%i
                     ENDCASE
    CASE f_modstart: cvf("MODSTART") // Start of module  
                     sectname%0 := 0
                     ENDCASE
    CASE f_modend:   cvf("MODEND") // End of module 
                     modletter := modletter+1
                     ENDCASE
    CASE f_global:   cvglobal(arg) // Global initialisation data
                     ENDCASE
    CASE f_string:   cvstring(arg) // String constant
                     ENDCASE
    CASE f_const:    cvconst(arg) // Large integer constant
                     ENDCASE

    CASE f_static:   cvstatic(arg) // Static variable or table
                     ENDCASE
    CASE f_mlab:     cvfm("MLAB") // Destination of jge0m
    	 	     writef("*n .global %s_M%c%n", arg, modletter, mval)
                     writef("*n%s_M%c%n:", arg, modletter, mval)
                     ENDCASE
    CASE f_lab:      cvfl("LAB") // ProgX4m label
    	 	     writef("*n .global %s_L%c%n", arg, modletter, lval)
                     writef("*n%s_L%c%n:", arg, modletter, lval)
                     ENDCASE
    CASE f_lstr:     cvfm("LSTR") // a := Mn   (pointer to string)
                     writef("*n adrp X4, %s_M%c%n @PAGE", arg, modletter, mval)
                     writef("*n add X4, X4, %s_M%c%n @PAGEOFF", arg,modletter, mval)
                     writef("*n lsr X4, X4, #3")
                     ENDCASE
    CASE f_entry:    cventry(arg) // Start of a function
                     ENDCASE

    CASE f_float:    cvf("FLOAT")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fix:      cvf("FIX")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fabs:     cvf("FABS")
                     writef("*n# unimplemented")
                     ENDCASE

    CASE f_fmul:     cvf("FMUL")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fdiv:     cvf("FDIV")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fadd:     cvf("FADD")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fsub:     cvf("FSUB")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fneg:     cvf("FNEG")
                     writef("*n# unimplemented")
                     ENDCASE

    CASE f_feq:      cvf("FEQ")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fne:      cvf("FNE")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fls:      cvf("FLS")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fgr:      cvf("FGR")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fle:      cvf("FLE")
                     writef("*n# unimplemented")
                     ENDCASE
    CASE f_fge:      cvf("FGE")
                     writef("*n# unimplemented")
                     ENDCASE
  }

  newline()
} REPEAT

AND opsize(k) = VALOF
{ // Returns the number of instructions needed to compute k out of 8-bit pieces
  LET s = 0
  UNLESS k RESULTIS 1
  WHILE k DO
  { // Find next 8-bit piece
    WHILE (k&3)=0 DO k := k>>2
    k, s := k>>8, s+1
  }
  RESULTIS s
}

AND genAddK(r, s, k) BE
{ // Generate code for: Rr := Rs + k
  LET opstr, sh = "add", 0
  LET neg, addch = FALSE, '+'

  IF k=0 DO
  { IF r=s RETURN
    writef("*n mov %s,%s", r, s)
    RETURN
  }
 
  IF opsize(-k)<opsize(k) DO opstr, k := "sub", -k

  TEST k <= #xFFFFFF THEN
  {
  writef("*n %s %s, %s, #%n // %x8", // add or sub
          opstr, r, s, k&#xFFF, k&#xFFF)

  k, sh := k>>12, sh+12

  WHILE k DO
  {
    writef("*n %s %s, %s, #%n, lsl #%n // %x8",  // add or sub
            opstr, r, r, k&#xFFF, sh, (k&#xFFF)<<sh)
    k, sh := k>>12, sh+12
  }
  } ELSE {
    genLoadK("X0", k);
    writef("*n %s %s, %s, X0", // add or sub
          opstr, r, s)
    
  }
}

AND genOpRRK(opstr, rd, rn, k) BE
{ // Generate code for: Rr := Rs op k
  // opstr is a data processing operation such as add or sub
  // Generate f rd,rn,#k
  // or       f rn,X0,#k' preceeded by instructions to set X0 to rn+k-k'
  LET sh = 0
  LET r = rn
  LET k8 = ?

  UNLESS opsize(k)=1 DO
  { genAddK(X0, rn, k)
    r := X0
  }

  k8 := (k & #xFF)<<sh
  k, sh := k>>8, sh+8

  WHILE k DO
  {

    writef("*n %s %s, %s, #%n // %x8",  // add or sub
            opstr, r, r, (k&#xFF)<<sh, (k&#xFF)<<sh)
    k, sh := k>>8, sh+8
  }

  writef("*n %s %s, %s,#%n // %x8",
          opstr, rd, r, k8, k8)
}

AND genLoadK(r, k) BE
{ LET sh = 0
  TEST k < 0 THEN
    {
    k := ~k;
    writef("*n movn %s, #%n // %x8", r, (k&#xFFFF)<<sh, k)

    k, sh := k>>16, sh+16

    WHILE k DO
      { 
      writef("*n// %x8 %x8", k, sh);
      writef("*n movk %s, #%n , LSL #%n", r, ((~k)&#xFFFF), sh)
      k, sh := k>>16, sh+16
      }
    }
  ELSE
    {
    writef("*n movz %s, #%n // %x8", r, (k&#xFFFF)<<sh, k)

    k, sh := k>>16, sh+16

    WHILE k DO
      {
      writef("*n// %x8 %x8", k, sh);
      writef("*n movk %s, #%n , LSL #%n", r, (k&#xFFFF), sh)
      k, sh := k>>16, sh+16
      }
    }
}

AND genLdrStr(opstr, rd, rn, k) BE
{ // opstr is "ldr" or "str"
  // Good for loading and storing locals and globals
  // If k is to large it uses register X0
  LET r, sh = rn, sh
  LET addstr = "add"
  LET plusch = '+'

  LET k12 = ?

  IF k<0 DO
  { k := -k
    addstr, plusch := "sub", '-'
  }

  k12 := k & #xFFF
  k, sh := k>>12, sh+12

  WHILE k DO
  { WHILE (k&3)=0 DO k, sh := k>>2, sh+2
    writef("*n %s X0, %s, #%n, LSL #%n // #%x8", addstr, r, (k & #xFF)<<sh, (k & #xFF)<<sh, sh)
    r := X0
    k, sh := k>>12, sh+12
  }

  writef("*n %s %s, [%s, #%c%n] // %x8", opstr, rd, r, plusch, k12, k12)
}

AND genCmpRK(r, k) BE
{ // This generates code to equivalent to cmp r, #k
  // If k is to large it uses register X0
  LET opstr, sh = "cmp", 0
  LET neg, addch = FALSE, '+'

  IF opsize(k)=1 DO
  { writef("*n cmp %s, #%n // %x8", r, k, k)
    RETURN
  }

  IF opsize(-k)=1 DO
  { writef("*n cmn %s, #%n // %x8", r, -k, -k)
    RETURN
  }

  genLoadK(X1, k)

  writef("*n cmp %s, X1", r)
}

AND cvf(s)   BE writef("// %s", s)
AND cvfp(s)  BE writef("// %t7 P%n", s, rdp())
AND cvfkp(s) BE writef("// %t7 K%n P%n", s, rdk(), rdp())
AND cvfg(s)  BE writef("// %t7 G%n", s, rdg())
AND cvfkg(s) BE writef("// %t7 K%n G%n", s, rdk(), rdg())
AND cvfkl(s) BE writef("// %t7 K%n _L%n", s, rdk(), rdl())
AND cvfpg(s) BE writef("// %t7 P%n G%n", s, rdp(), rdg())
AND cvfk(s)  BE writef("// %t7 K%n", s, rdk())
AND cvfw(s)  BE writef("// %t7 W%n", s, rdw())
AND cvfl(s)  BE writef("// %t7 _L%n", s, rdl())
AND cvfm(s)  BE writef("// %t7_M%n", s, rdm())

AND cvswl(arg) BE
{ STATIC { cnt = 0 }
  LET n    = rdk()
  LET dlab = rdl()
  cnt := cnt + n + dlab + 1
  writef("// SWL K%n _N%n", n, dlab)
  writef("*n adrp X1, %s_K%n_M%c%n @PAGE", arg, cnt, modletter, dlab)
  writef("*n add X1, X1, %s_K%n_M%c%n @PAGEOFF", arg, cnt, modletter, dlab)
  genCmpRK(X4, n)
  writef("*n ldrsw X9, [X1, X4, lsl #2]")
  writef("*n add X1, X1, X9")
  writef("*n br X1")
  writef("*n .p2align 2, 0x0*n")
  writef("*n%s_K%n_M%c%n:", arg, cnt, modletter, dlab)
  
  FOR i = 1 TO n DO
  { LET l = rdl()
    writef("*n .long %s_L%c%n - %s_K%n_M%c%n // cvswl", arg, modletter, l, arg, cnt, modletter, dlab)
  }

  writef("*n .section __TEXT, __text,regular,pure_instructions")
}

AND cvswb(arg) BE
{ LET n    = rdk()
  LET dlab = rdl()
  writef("// SWB K%n _L%n", n, dlab)
  FOR i = 1 TO n DO 
  { LET k = rdk()
    LET l = rdl()
    writef("*n// K%n _L%n", k, l)
    genCmpRK(X4, k)
    writef("*n beq %s_L%c%n", arg, modletter, l)
  }
  writef("*n b %s_L%c%n", arg, modletter, dlab)
//  writef("*n .ltorg")
}

AND cvglobal(arg) BE
{ LET n = rdk()
  writef("// GLOBAL K%n*n", n)
  IF sectname%0=0 FOR i = 0 TO 4 DO sectname%i := "prog"%i
  writef("*n .global _%s*n", sectname)
  writef("_%s:*n", sectname)
  writef("*n .global %s_%s*n", arg, sectname)
  writef("%s_%s:*n", arg, sectname)
  writef("*n// On entry X0 points to the Global vector")
  FOR i = 1 TO n DO
  { LET g = rdg()
    LET n = rdl()
    writef("*n// G%n _L%n", g, n)
    //writef("*n adrl X1, _L%c%n", modletter, n)
    writef("*n adrp X1, %s_L%c%n @PAGE", arg, modletter, n)
    writef("*n add X1, X1, %s_L%c%n @PAGEOFF", arg, modletter, n)
    genLdrStr("str", X1, X0, 8*gval)
  }
  writef("*n// G%n", rdg())
  writef("*n ret*n")
//  writef("*n .ltorg*n")
}

AND rdchars() = VALOF
{ LET n = rdk()
  charv%0 := n
  FOR i = 1 TO n DO charv%i := rdc()
  RESULTIS n
}

AND cvstring(arg) BE
{ // Place strings in the data (read/write) section
  LET lab = rdm()
  LET n = rdchars()
  writef("*n// STRING_M%n ", n)
  writef("*n .section __TEXT,__cstring,cstring_literals")
  writef("*n .p2align 3, 0x0*n")
  writef("*n .global %s_M%c%n", arg, modletter, lab)
  writef("*n%s_M%c%n:", arg, modletter, lab)
  writef("*n .byte %n *n .asciz *"", n)
  FOR i = 1 TO n DO { SWITCHON charv%i INTO {
    CASE '*n': writef("\n"); ENDCASE
    CASE 34: writef("\*""); ENDCASE
    DEFAULT: writef("%c", charv%i)
    } }
  writef("*"*n .section __TEXT, __text,regular,pure_instructions")
}

AND cvconst(arg) BE
{ // Place constants in the text (read only) section
  LET lab = rdm()
  LET w = rdw()
  writef("// CONST  _M%n %n", lab, w)
  writef("*n .section __TEXT, __const")
  writef("*n .p2align 3, 0x0*n")
  writef("*n .global %s_M%c%n", arg, modletter, lab)
  writef("*n%s_M%c%n:", arg, modletter, lab)
  writef("*n .dword %n // cvconst", w)
  writef("*n .section __TEXT, __text,regular,pure_instructions")
}

AND cvstatic(arg) BE
{ // Place STATIC variables in the data (read/write) section
  LET lab = rdl()
  LET n = rdk()
  writef("// STATIC _L%n K%n", lab, n)
  writef("*n .section __DATA, __data")
  writef("*n .p2align 3, 0x0*n")
  writef("*n .global %s_L%c%n", arg, modletter, lab)
  writef("*n%s_L%c%n:", arg, modletter, lab)
  FOR i = 1 TO n DO { writef("*n// W%n", rdw())
                      writef("*n .dword %n // cvstatic", wval)
                    }
  writef("*n .section __TEXT, __text,regular,pure_instructions")
}

AND cvfs(s) BE
{ LET n = rdchars()
  writef("// %t7 K%n", s, n)
  FOR i = 1 TO n DO writef(" C%n", charv%i)
}

AND cventry(arg) BE
{ // On entry
  // X1 = <entry address>
  // X2 = <new P pointer>
  // X4 = <first arg>
  // X10 = <old P pointer>
  LET n = rdchars()
  LET op = rdf()
  LET lab = rdl()
  writef("*n .global %s_%s_%n", arg, charv, lab)
  writef("*n%s_%s_%n:", arg, charv, lab)
  writef("*n// Entry to: %s*n", charv)
  writef("// %t7 K%n", "ENTRY", n)
  FOR i = 1 TO n DO writef(" C%n", charv%i)
  newline()
  TEST op=f_lab THEN writef("// LAB     _L%n*n", lab)
                ELSE writef("// Bad op F%n _L%n*n", op, lab)
  writef("*n .global %s_L%c%n", arg, modletter, lab)
  writef("*n%s_L%c%n:", arg, modletter, lab)
  writef("*n stp X10,lr, [X2], #16")  // NP!0, NP!1 := P, <return> 
  writef("*n stp X1,X4, [X2]")    // NP!2, NP!3  := X1, X4  -- <entry>, <arg1>
  writef("*n sub X10, X2, #16")        // P    := NP
  // P -> [<old P>, <return addr>, <entry addr>, <first arg>, ... ]
}
